export const ERROR_CODES = {
  VALIDATION: 'VALIDATION_ERROR',
  AUTH: 'AUTH_REQUIRED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER: 'INTERNAL_SERVER_ERROR',
  AI: 'AI_ERROR',
  NETWORK: 'NETWORK_ERROR',
  UNKNOWN: 'UNKNOWN_ERROR',
} as const;

export const CODE_BY_STATUS_CODE: Record<number, string> = {
  400: ERROR_CODES.VALIDATION,
  401: ERROR_CODES.AUTH,
  403: ERROR_CODES.FORBIDDEN,
  404: ERROR_CODES.NOT_FOUND,
  429: ERROR_CODES.TOO_MANY_REQUESTS,
  500: ERROR_CODES.INTERNAL_SERVER,
  502: ERROR_CODES.AI,
};

export const STATUS_CODE_BY_CODE: Record<string, number> = {
  [ERROR_CODES.VALIDATION]: 400,
  [ERROR_CODES.AUTH]: 401,
  [ERROR_CODES.FORBIDDEN]: 403,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.TOO_MANY_REQUESTS]: 429,
  [ERROR_CODES.INTERNAL_SERVER]: 500,
  [ERROR_CODES.AI]: 502,
};

export const FALLBACK_MESSAGE = 'Something went wrong';
export const FALLBACK_STATUS_CODE = STATUS_CODE_BY_CODE[ERROR_CODES.INTERNAL_SERVER];